DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS (
id INT AUTO_INCREMENT  PRIMARY KEY,
name VARCHAR(50) NOT NULL,
birthDate DATE NOT NULL,
countryResidance VARCHAR(50) NOT NULL,
phoneNumber VARCHAR(15) ,
gender VARCHAR(1) NOT NULL
);